# Generated by Django 4.1.4 on 2023-02-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentrymodel',
            name='download',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='download',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download', to='blog.blogentrymodel', verbose_name='Файл'),
        ),
    ]
