# Generated by Django 4.1.4 on 2023-03-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shops_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='stocks',
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=15, verbose_name='Наименование товара')),
                ('stocks', models.CharField(blank=True, max_length=300, verbose_name='Акции')),
                ('offers', models.CharField(blank=True, max_length=300, verbose_name='Предложения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shops')),
            ],
        ),
    ]
