# Generated by Django 4.1.4 on 2023-03-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_name_shops_shop_name_remove_shops_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='shop',
        ),
        migrations.AddField(
            model_name='shops',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.items'),
        ),
    ]
