# Generated by Django 4.1.4 on 2023-03-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_items_shop_shops_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='item',
        ),
        migrations.AddField(
            model_name='items',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shops'),
        ),
    ]
