# Generated by Django 4.1.4 on 2023-03-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_shops_item_items_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.profile'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=300, verbose_name='Наименование товара'),
        ),
    ]
