# Generated by Django 4.1.4 on 2023-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_balance_profile_alter_items_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
