# Generated by Django 4.1.4 on 2023-03-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_items_shop_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.balance')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.items')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
