# Generated by Django 4.1.4 on 2023-03-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_history_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.balance')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.items')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
